### ISSUE TITLE
SIGPIPE from journald prevents restart

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/cmd#13]
Go does not ignore SIGPIPE for fd 1 & 2 (stdout & stderr).  
This can be a problem when programs written in Go run with systemd.

Quote from https://golang.org/pkg/os/signal/
> If the program has not called Notify to receive SIGPIPE signals, then the behavior depends on the file descriptor number. A write to a broken pipe on file descriptors 1 or 2 (standard output or standard error) will cause the program to exit with a SIGPIPE signal. A write to a broken pipe on some other file descriptor will take no action on the SIGPIPE signal, and the write will fail with an EPIPE error.

A typical systemd service configuration looks like:

```
[Service]
Type=simple
ExecStart=/path/to/go/program
Restart=on-failure
```

Services configured like this have its stdout and stderr connected with systemd-journald.
Journald is infamous for raising SIGPIPE when it restarts.  If this happens, Go programs that do not install SIGPIPE handlers will die because of the aforementioned specification.

Worse, since systemd regards it normal when programs exited with SIGPIPE because the
default value of `SuccessExitStatus` includes SIGPIPE.  As a consequence, even though the
service is configured with `Restart=on-failure`, the service will stop **cleanly** when it receives
SIGPIPE from journald.

**Comment by ymmt2005** [comment]
systemd.exec specifies `JOURNAL_STREAM` environment variable is set if the program
is spawned by systemd and its stdout/err is connected to journald.
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#%24JOURNAL_STREAM

**Comment by yutannihilation** [comment]
Note that `JOURNAL_STREAM` is only available on the latest versions as this feature is added at systemd 231: https://github.com/systemd/systemd/blob/92d6f2f34895a5f126493a2fd7ff8fb660a84a22/NEWS#L763-L771.

* Debian Jessie: https://manpages.debian.org/jessie/systemd/systemd.exec.5.en.html
* Ubuntu 16.04: http://manpages.ubuntu.com/manpages/xenial/man5/systemd.exec.5.html

**Comment by ymmt2005** [comment]
@yutannihilation @nojima 
Hmm, systemd on Ubuntu 16.04 sets only these envvars...

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=en_US.UTF-8
PWD=/
```

**Comment by ymmt2005** [comment]
@nojima and I agreed that we should just ignore SIGPIPE and make it a specification of the framework.
Although we could manage to detect systemd through `/proc/self/cgroup`, simplicity wins.
