### ISSUE TITLE
When journald restarts, program should exit abnormally.

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/cmd#15]
In #13, we just ignored SIGPIPE upon journald restarts.

As a consequence, programs using this framework will not fail
on journald restart but now they may stack when writing logs to
stdout/stderr pipes.

I don't know the exact reason but as systemd & journald is so flaky,
and SIGPIPE is treated as normal exit condition by systemd, we need
to catch SIGPIPE on stdout/stderr and exit abnormally, say, with
exit condition 2.

**Comment by ymmt2005** [comment]
@yutannihilation @nojima 
Is this ok?

**Comment by nojima** [comment]
I just noticed that systemd has an option IgnoreSIGPIPE. And it is true by default.

```
       IgnoreSIGPIPE=
           Takes a boolean argument. If true, causes SIGPIPE to be ignored in the executed process.
           Defaults to true because SIGPIPE generally is useful only in shell pipelines.
```

Therefore, it is possible that SIGPIPE is still ignored although we explicitly handle SIGPIPE to exit abnormally.

However, the existence of this option contradicts our experience ― our daemons under systemd were killed by SIGPIPE.  I suppose that this option does not work in some condition.

**Comment by ymmt2005** [comment]
@nojima 
Yes I know.  With that option, systemd installs a signal handler for SIGPIPE
before executing the service.  However, Go overrides that handler in order to
manually handle SIGPIPE for stdout and stderr.  What a misfortune.

**Comment by ymmt2005** [comment]
The above description is wrong.  Go does not override the SIGPIPE handler.
Instead, it manually raise SIGPIPE if EPIPE error is returned from Write to fd 1 & 2.
