### ISSUE TITLE
Fix SIGPIPE handling, take 3

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/cmd#17]
In #13, we just ignored SIGPIPE from stdout and stderr.
The result was process hangup after journald crashed and restarted.
Ignoring SIGPIPE and ignoring EPIPE from stdout and stderr connected to journald
will eventually blocks the process if we continue to write to stdout or stderr.

In #15, we handled SIGPIPE and exit with status code 2.
This worked, but we started to get SIGPIPEs from file descriptors other than stdout
and stderr, causing the programs using this framework crash unexpectedly often
due to broken network connections.

We rethink how to resolve these and those issues related to Go and systemd-journald.

1. Ignore SIGPIPE completely just as in #13, but only when the program runs as a systemd service.
    The default behavior of Go that raises SIGPIPE only for stdout and stderr is reasonable if the program runs outside of systemd.

2. Handle EPIPE and exit with status code 5 in [the logging package](https://github.com/cybozu-go/log/issues/11).
    We should ignore SIGPIPE for systemd services but should **not** ignore EPIPE from stdout and stderr.

**Comment by ymmt2005** [comment]
This issue should address the first.

The framework will revert to ignore SIGPIPE, but this time only if the program runs as a systemd service.
To determine whether a program is running as a systemd service, we can see either:

1. [`JOURNAL_STREAM`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#%24JOURNAL_STREAM) envvar for the recent systemd, or
2. /proc/self/cgroup

For 2, if the process runs as a systemd service, its cgroup name should look like:
```
$ sudo grep :name=systemd: /proc/XXXXXXXX/cgroup 
1:name=systemd:/system.slice/hoge.service
```

**Comment by ymmt2005** [comment]
@nojima PTAL

**Comment by nojima** [comment]
OK
